[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_rng = "FaxBGrEXfDT7USLAwNDQCtXvAJW4W44VdLFa5YVb6p3G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
